# Generated by Django 6.0.6 on 2026-06-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article headline, as published by the source.', max_length=500)),
                ('source', models.CharField(help_text="Human-readable source name, e.g. 'TechCrunch', 'Google News'.", max_length=150)),
                ('url', models.URLField(help_text='Canonical article URL. Unique — used as the dedupe key on ingestion.', max_length=1000, unique=True)),
                ('summary', models.TextField(blank=True, help_text='RSS description/snippet. Short summary, not full article text.')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the source published this article (from RSS feed metadata).', null=True)),
                ('raw_content', models.TextField(blank=True, help_text='Optional fuller text content, if the feed provides more than a snippet.')),
                ('matched_keywords', models.CharField(blank=True, help_text='Comma-separated keywords/phrases this article was matched to during trend detection. Filled in by the detect_trends command, not on ingestion.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this article was ingested into our database (not published date).')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
