# Generated by Django 6.0.6 on 2026-07-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS / News'), ('youtube', 'YouTube'), ('reddit', 'Reddit')], default='rss', help_text='Which monitoring layer this item came from.', max_length=20),
        ),
    ]
