# Generated by Django 6.0.6 on 2026-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True once the user has clicked the confirmation link sent to their email.'),
        ),
    ]
