# Generated by Django 6.0.6 on 2026-06-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The topic/keyword phrase, e.g. 'AI Agents', 'Startup Grants'.", max_length=200, unique=True)),
                ('trend_score', models.FloatField(default=0.0, help_text='Frequency/velocity-based score. Higher means more articles are mentioning this topic, weighted toward recency.')),
                ('relevance_score', models.IntegerField(default=0, help_text='0-100 score: how useful/relevant this is to founders and entrepreneurs.')),
                ('source_count', models.IntegerField(default=0, help_text='Number of distinct articles mentioning this trend.')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('briefed', 'Briefed'), ('archived', 'Archived')], default='detected', help_text='Pipeline state: detected -> briefed (has a ContentBrief) -> archived.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this trend was first detected.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time trend_score/relevance_score were recalculated.')),
                ('articles', models.ManyToManyField(blank=True, help_text="Articles that contributed evidence for this trend (shown as 'Sources').", related_name='trends', to='articles.article')),
            ],
            options={
                'ordering': ['-trend_score'],
            },
        ),
    ]
