"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env at project root (OPENAI_API_KEY, etc.)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-2xn(i)w6c+q=0lj@&%n=@7am*uvr0i+%-eelzo2@ls(xuy$!y&',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Trendjack Hunter apps
    'core',
    'articles',
    'trends',
    'briefs',
    'accounts',
]

# -----------------------------------------------------------------------
# Trendjack Hunter custom settings
# -----------------------------------------------------------------------

# OpenAI API key, loaded from .env — used by briefs/services/openai_client.py
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Model used for content brief generation (cheap + fast for hackathon use)
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o-mini')

# Minimum entrepreneur-relevance score (0-100) a trend needs before
# generate_briefs will bother calling OpenAI on it. Saves API calls on noise.
MIN_RELEVANCE_SCORE_FOR_BRIEF = int(os.environ.get('MIN_RELEVANCE_SCORE_FOR_BRIEF', '40'))

# YouTube Data API v3 — used by articles/services/youtube_collector.py
# Get a key at https://console.cloud.google.com/apis/credentials
# (enable "YouTube Data API v3" on the project first). Free for this volume.
YOUTUBE_API_KEY = os.environ.get('YOUTUBE_API_KEY', '')

# Reddit API (OAuth2 script app) — used by articles/services/reddit_collector.py
# Create a "script" app at https://www.reddit.com/prefs/apps
REDDIT_CLIENT_ID = os.environ.get('REDDIT_CLIENT_ID', '')
REDDIT_CLIENT_SECRET = os.environ.get('REDDIT_CLIENT_SECRET', '')
REDDIT_USER_AGENT = os.environ.get('REDDIT_USER_AGENT', 'TrendjackHunter/1.0')

# -----------------------------------------------------------------------
# Accounts / Subscriptions / IntaSend settings
# -----------------------------------------------------------------------

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:subscribe'
LOGOUT_REDIRECT_URL = 'core:home'

# IntaSend API keys — get these from your IntaSend dashboard (Settings > API keys).
# Use the sandbox keys while INTASEND_TEST_MODE is True.
INTASEND_PUBLISHABLE_KEY = os.environ.get('INTASEND_PUBLISHABLE_KEY', '')
INTASEND_SECRET_KEY = os.environ.get('INTASEND_SECRET_KEY', '')
INTASEND_TEST_MODE = os.environ.get('INTASEND_TEST_MODE', 'True') == 'True'

# A secret string you configure in the IntaSend dashboard under
# Settings > Webhooks. IntaSend echoes this back in every webhook payload
# so we can verify the request actually came from IntaSend.
INTASEND_WEBHOOK_CHALLENGE = os.environ.get('INTASEND_WEBHOOK_CHALLENGE', '')

# Subscription prices in Kenyan Shillings.
SUBSCRIPTION_PRICE_MONTHLY_KES = os.environ.get('SUBSCRIPTION_PRICE_MONTHLY_KES', '500')
SUBSCRIPTION_PRICE_YEARLY_KES = os.environ.get('SUBSCRIPTION_PRICE_YEARLY_KES', '5000')

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # ... rest of your existing middleware stays exactly as-is
   'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}

if not DATABASES['default']:
    raise Exception(
        "DATABASE_URL is not set. Add it to your .env file — "
        "no default is provided for security reasons."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Email (Resend SMTP) ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.resend.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "resend"
EMAIL_HOST_PASSWORD = os.environ.get("RESEND_API_KEY")
DEFAULT_FROM_EMAIL = "Trendjack Hunter <onboarding@resend.dev>"

