from django.db import models
from trends.models import Trend


class ContentBrief(models.Model):
    """
    AI-generated content brief for a single Trend.

    Generated by the generate_briefs management command, which sends the
    Trend's name + evidence article summaries to OpenAI and stores the
    structured result here. One brief per trend (OneToOne) — re-running
    generate_briefs on an already-briefed trend updates the existing row
    rather than creating duplicates.
    """

    trend = models.OneToOneField(
        Trend,
        on_delete=models.CASCADE,
        related_name="brief",
        help_text="The trend this brief was generated for.",
    )
    why_trending = models.TextField(
        help_text="AI-generated explanation of why this topic is trending right now.",
    )
    why_entrepreneurs_care = models.TextField(
        help_text="AI-generated explanation of why founders/entrepreneurs should pay attention.",
    )
    content_angle = models.TextField(
        help_text="Suggested narrative angle for content built around this trend.",
    )
    linkedin_post_idea = models.TextField(
        help_text="Ready-to-adapt LinkedIn post concept.",
    )
    instagram_reel_idea = models.TextField(
        help_text="Ready-to-adapt Instagram Reel concept/script outline.",
    )
    suggested_hook = models.CharField(
        max_length=300,
        help_text="A short, punchy opening line/hook for content.",
    )
    suggested_title = models.CharField(
        max_length=300,
        help_text="A suggested headline/title for a piece of content.",
    )
    estimated_lifespan = models.CharField(
        max_length=100,
        blank=True,
        help_text=(
            "AI-estimated remaining relevance window for this trend, e.g. "
            "'2-3 days', '6-12 hours', '1-2 weeks'."
        ),
    )
    video_script = models.TextField(
        blank=True,
        help_text=(
            "A ready-to-shoot 30-60 second video script (hook, body beats, "
            "CTA) adapted to this trend."
        ),
    )
    remix_template = models.TextField(
        blank=True,
        help_text=(
            "Explains the trend's underlying format/structure and how to "
            "remix it into a founder/business story — reusable even after "
            "this specific trend fades."
        ),
    )
    urgency_score = models.IntegerField(
        default=0,
        help_text="0-100: how time-sensitive this content opportunity is (higher = act fast).",
    )
    raw_ai_response = models.TextField(
        blank=True,
        help_text="Raw JSON response from OpenAI, kept for debugging/audit purposes.",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When this brief was generated.",
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last time this brief was regenerated.",
    )

    class Meta:
        ordering = ["-urgency_score"]

    def __str__(self):
        return f"Brief: {self.trend.name}"
