# Generated by Django 6.0.6 on 2026-06-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_trending', models.TextField(help_text='AI-generated explanation of why this topic is trending right now.')),
                ('why_entrepreneurs_care', models.TextField(help_text='AI-generated explanation of why founders/entrepreneurs should pay attention.')),
                ('content_angle', models.TextField(help_text='Suggested narrative angle for content built around this trend.')),
                ('linkedin_post_idea', models.TextField(help_text='Ready-to-adapt LinkedIn post concept.')),
                ('instagram_reel_idea', models.TextField(help_text='Ready-to-adapt Instagram Reel concept/script outline.')),
                ('suggested_hook', models.CharField(help_text='A short, punchy opening line/hook for content.', max_length=300)),
                ('suggested_title', models.CharField(help_text='A suggested headline/title for a piece of content.', max_length=300)),
                ('urgency_score', models.IntegerField(default=0, help_text='0-100: how time-sensitive this content opportunity is (higher = act fast).')),
                ('raw_ai_response', models.TextField(blank=True, help_text='Raw JSON response from OpenAI, kept for debugging/audit purposes.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this brief was generated.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this brief was regenerated.')),
                ('trend', models.OneToOneField(help_text='The trend this brief was generated for.', on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='trends.trend')),
            ],
            options={
                'ordering': ['-urgency_score'],
            },
        ),
    ]
