# Generated by Django 6.0.6 on 2026-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbrief',
            name='estimated_lifespan',
            field=models.CharField(blank=True, help_text="AI-estimated remaining relevance window for this trend, e.g. '2-3 days', '6-12 hours', '1-2 weeks'.", max_length=100),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='remix_template',
            field=models.TextField(blank=True, help_text="Explains the trend's underlying format/structure and how to remix it into a founder/business story — reusable even after this specific trend fades."),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='video_script',
            field=models.TextField(blank=True, help_text='A ready-to-shoot 30-60 second video script (hook, body beats, CTA) adapted to this trend.'),
        ),
    ]
